### ISSUE TITLE
Python unhashable type: 'list' error while running on Windows 

### ISSUE THREAD

**Issue by fatihsirin** [OWNsecurity/fastir_artifacts#18]
While running fastir_artifacts.exe on a Windows 11 host, there is no custom configuration

2023-05-08 13:10:33,317 - PROGRESS - Loading artifacts ...
2023-05-08 12:10:39,803 - PROGRESS - Collecting artifacts from 54 sources ...
Traceback (most recent call last):
  File "fastir_artifacts.py", line 134, in <module>
  File "fastir_artifacts.py", line 115, in main
  File "fastir\common\collector.py", line 52, in collect
  File "fastir\common\filesystem.py", line 322, in collect
  File "fastir\common\filesystem.py", line 72, in collect
  File "fastir\common\path_components.py", line 77, in _generate
  File "fastir\common\path_components.py", line 93, in _generate
  File "fastir\common\path_components.py", line 54, in _generate
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  [Previous line repeated 1 more time]
  File "fastir\common\path_components.py", line 58, in _recurse_from_dir
  File "fastir\common\path_components.py", line 21, in list_directory
  File "fastir\common\filesystem.py", line 140, in list_directory
TypeError: unhashable type: 'list'
[21780] Failed to execute script 'fastir_artifacts' due to unhandled exception!

**Comment by gregorygui** [comment]
Hi,

I try to run the latest version of FastIR on a fresh Windows 11 (Home) virtual machine, and no errors have been raised.

Which version do you use ? Do you have custom artefacts ?

**Comment by fatihsirin** [comment]
Hi,

I upgraded all packages and Python with windows 11 update, problem looks its solved. there wasn't any custom artefacts
