### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by edu-lance** [OWNsecurity/fastir_artifacts#21]
```python

self._entries_cache = {}
self._entries_cache_last = []

#....

first = self._entries_cache_last.pop(0)
del self._entries_cache[first]

entries = []
directory = path_object.obj

#....
self._entries_cache[path_object.path] = entries
self._entries_cache_last.append(entries)
```
delete by value?

**Comment by jfisto** [comment]
Hi
I also ran into this problem.


```
fastir_artifacts>fastir_artifacts.exe
2025-09-30 11:01:36,930 - PROGRESS - Loading artifacts ...
2025-09-30 08:01:39,641 - PROGRESS - Collecting artifacts from 54 sources ...
Traceback (most recent call last):
  File "fastir_artifacts.py", line 134, in <module>
  File "fastir_artifacts.py", line 115, in main
  File "fastir\common\collector.py", line 52, in collect
  File "fastir\common\filesystem.py", line 322, in collect
  File "fastir\common\filesystem.py", line 72, in collect
  File "fastir\common\path_components.py", line 77, in _generate
  File "fastir\common\path_components.py", line 93, in _generate
  File "fastir\common\path_components.py", line 54, in _generate
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  File "fastir\common\path_components.py", line 60, in _recurse_from_dir
  File "fastir\common\path_components.py", line 58, in _recurse_from_dir
  File "fastir\common\path_components.py", line 21, in list_directory
  File "fastir\common\filesystem.py", line 140, in list_directory
TypeError: unhashable type: 'list'
[6372] Failed to execute script 'fastir_artifacts' due to unhandled exception
```
